### ISSUE TITLE
Custom Quirks "pencils" too small - make clicking tricky

### ISSUE THREAD

**Issue by kindredsparrow** [gregallensworth/BattleTechCalculator#11]

**Comment by gregallensworth** [comment]
Commit 432fce4 improves a few things:
- Label font and also edit-button font are larger
- The edit-button now has padding-left instead of margin-left, so its hitbox is larger
- The edit-button now has padding-right, increasing the size of its hitbox

**Comment by kindredsparrow** [comment]
Excellent!  Thank you :)

L
